### ISSUE TITLE
Fatal error - Interface not found

### ISSUE THREAD

**Issue by janbok** [susam/mathb#9]
I installed app including the thirdparty software and upon launching mathbin.php, I have got

`Fatal error: Interface 'Michelf\MarkdownInterface' not found in /home/bok/WWW/mathb/thirdparty/php-markdown/Michelf/Markdown.php on line 20`

By searching the term in Google, I have found out that this error comes up in many error logs. But I haven't found any solution. Where is the problem?

**Comment by susam** [comment]
Follow the steps provided in the [Source code setup](https://github.com/susam/mathb#source-code-setup) section. In the end, confirm that the `thirdparty` directory is setup as explained there.

**Comment by janbok** [comment]
Well, I've found out where the problem was. I needed to change 

`
require __DIR__ . '/thirdparty/php-markdown/Michelf/Markdown.php';`

to


`require __DIR__ . '/thirdparty/php-markdown/Michelf/Markdown.inc.php';`

in `mathbin.php`

**Comment by susam** [comment]
Thanks for finding the cause of the issue and sending a pull request.

The MathB application running on http://mathb.in/ server is using an older version of the php-markdown library. The version of the library used on the server is 1.3 and it doesn't have Markdown.inc.php. That's why I haven't faced this issue earlier on the server.

```
$ head -n 5 php-markdown/Readme.md
PHP Markdown
============

PHP Markdown Lib 1.3 - 11 Apr 2013

$ tree php-markdown
php-markdown
+-- composer.json
+-- License.md
+-- Michelf
¦   +-- MarkdownExtra.php
¦   +-- Markdown.php
+-- Readme.md
+-- Readme.php

1 directory, 6 files
```

I will update the php-markdown library on the server, take a look at your pull request and merge it by 06-Mar-2015.

**Comment by janbok** [comment]
OK, thanks!

Jan
